// Code generated by protoc-gen-go. DO NOT EDIT.
// source: network.proto

/*
Package d7024e is a generated protocol buffer package.

It is generated from these files:
	network.proto

It has these top-level messages:
	ContactPacket
	FilePacket
	KademliaPacket
*/
package d7024e

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ContactPacket struct {
	Address string `protobuf:"bytes,1,opt,name=Address" json:"Address,omitempty"`
	ID      string `protobuf:"bytes,2,opt,name=ID" json:"ID,omitempty"`
}

func (m *ContactPacket) Reset()                    { *m = ContactPacket{} }
func (m *ContactPacket) String() string            { return proto.CompactTextString(m) }
func (*ContactPacket) ProtoMessage()               {}
func (*ContactPacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ContactPacket) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ContactPacket) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type FilePacket struct {
	ID   string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *FilePacket) Reset()                    { *m = FilePacket{} }
func (m *FilePacket) String() string            { return proto.CompactTextString(m) }
func (*FilePacket) ProtoMessage()               {}
func (*FilePacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FilePacket) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *FilePacket) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type KademliaPacket struct {
	SourceAddress      string           `protobuf:"bytes,1,opt,name=SourceAddress" json:"SourceAddress,omitempty"`
	SourceID           string           `protobuf:"bytes,2,opt,name=SourceID" json:"SourceID,omitempty"`
	DestinationAddress string           `protobuf:"bytes,3,opt,name=DestinationAddress" json:"DestinationAddress,omitempty"`
	Procedure          string           `protobuf:"bytes,4,opt,name=Procedure" json:"Procedure,omitempty"`
	ReturnedPacket     bool             `protobuf:"varint,5,opt,name=ReturnedPacket" json:"ReturnedPacket,omitempty"`
	RandomID           int32            `protobuf:"varint,6,opt,name=RandomID" json:"RandomID,omitempty"`
	PacketID           int32            `protobuf:"varint,7,opt,name=PacketID" json:"PacketID,omitempty"`
	TargetID           string           `protobuf:"bytes,8,opt,name=TargetID" json:"TargetID,omitempty"`
	Contacts           []*ContactPacket `protobuf:"bytes,9,rep,name=Contacts" json:"Contacts,omitempty"`
	File               *FilePacket      `protobuf:"bytes,10,opt,name=File" json:"File,omitempty"`
}

func (m *KademliaPacket) Reset()                    { *m = KademliaPacket{} }
func (m *KademliaPacket) String() string            { return proto.CompactTextString(m) }
func (*KademliaPacket) ProtoMessage()               {}
func (*KademliaPacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *KademliaPacket) GetSourceAddress() string {
	if m != nil {
		return m.SourceAddress
	}
	return ""
}

func (m *KademliaPacket) GetSourceID() string {
	if m != nil {
		return m.SourceID
	}
	return ""
}

func (m *KademliaPacket) GetDestinationAddress() string {
	if m != nil {
		return m.DestinationAddress
	}
	return ""
}

func (m *KademliaPacket) GetProcedure() string {
	if m != nil {
		return m.Procedure
	}
	return ""
}

func (m *KademliaPacket) GetReturnedPacket() bool {
	if m != nil {
		return m.ReturnedPacket
	}
	return false
}

func (m *KademliaPacket) GetRandomID() int32 {
	if m != nil {
		return m.RandomID
	}
	return 0
}

func (m *KademliaPacket) GetPacketID() int32 {
	if m != nil {
		return m.PacketID
	}
	return 0
}

func (m *KademliaPacket) GetTargetID() string {
	if m != nil {
		return m.TargetID
	}
	return ""
}

func (m *KademliaPacket) GetContacts() []*ContactPacket {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *KademliaPacket) GetFile() *FilePacket {
	if m != nil {
		return m.File
	}
	return nil
}

func init() {
	proto.RegisterType((*ContactPacket)(nil), "d7024e.ContactPacket")
	proto.RegisterType((*FilePacket)(nil), "d7024e.FilePacket")
	proto.RegisterType((*KademliaPacket)(nil), "d7024e.KademliaPacket")
}

func init() { proto.RegisterFile("network.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0x69, 0xf7, 0xaf, 0xbb, 0x73, 0x7b, 0xb8, 0x20, 0x04, 0xf1, 0xa1, 0x0c, 0x19, 0x7d,
	0x2a, 0x73, 0x0a, 0xe2, 0xa3, 0x58, 0x84, 0xe2, 0xcb, 0x88, 0x7e, 0x81, 0xd8, 0x5c, 0xa4, 0x6c,
	0x4b, 0x24, 0xcd, 0xf0, 0xa3, 0xfb, 0x2a, 0x4d, 0x96, 0x8e, 0x8a, 0x6f, 0x39, 0xe7, 0x77, 0x6e,
	0x72, 0xc3, 0x81, 0xb9, 0x22, 0xfb, 0xad, 0xcd, 0x2e, 0xff, 0x32, 0xda, 0x6a, 0x1c, 0xcb, 0x87,
	0xf5, 0xe6, 0x9e, 0x96, 0x8f, 0x30, 0x7f, 0xd6, 0xca, 0x8a, 0xca, 0x6e, 0x45, 0xb5, 0x23, 0x8b,
	0x0c, 0x26, 0x4f, 0x52, 0x1a, 0x6a, 0x1a, 0x16, 0xa5, 0x51, 0x36, 0xe5, 0x41, 0xe2, 0x02, 0xe2,
	0xb2, 0x60, 0xb1, 0x33, 0xe3, 0xb2, 0x58, 0xae, 0x01, 0x5e, 0xea, 0x3d, 0x9d, 0xe6, 0x3c, 0x8d,
	0x02, 0x45, 0x84, 0x61, 0x21, 0xac, 0x70, 0xf9, 0x0b, 0xee, 0xce, 0xcb, 0x9f, 0x18, 0x16, 0xaf,
	0x42, 0xd2, 0x61, 0x5f, 0x8b, 0xd3, 0xd8, 0x0d, 0xcc, 0xdf, 0xf4, 0xd1, 0x54, 0xd4, 0x7f, 0xb4,
	0x6f, 0xe2, 0x15, 0x24, 0xde, 0xe8, 0x16, 0xe8, 0x34, 0xe6, 0x80, 0x05, 0x35, 0xb6, 0x56, 0xc2,
	0xd6, 0x5a, 0x85, 0x6b, 0x06, 0x2e, 0xf5, 0x0f, 0xc1, 0x6b, 0x98, 0x6e, 0x8d, 0xae, 0x48, 0x1e,
	0x0d, 0xb1, 0xa1, 0x8b, 0x9d, 0x0d, 0x5c, 0xc1, 0x82, 0x93, 0x3d, 0x1a, 0x45, 0xd2, 0x6f, 0xc8,
	0x46, 0x69, 0x94, 0x25, 0xfc, 0x8f, 0xdb, 0x6e, 0xc4, 0x85, 0x92, 0xfa, 0x50, 0x16, 0x6c, 0x9c,
	0x46, 0xd9, 0x88, 0x77, 0xba, 0x65, 0x3e, 0x55, 0x16, 0x6c, 0xe2, 0x59, 0xd0, 0x2d, 0x7b, 0x17,
	0xe6, 0xd3, 0xb1, 0xc4, 0xff, 0x24, 0x68, 0xbc, 0x85, 0xe4, 0xd4, 0x45, 0xc3, 0xa6, 0xe9, 0x20,
	0x9b, 0x6d, 0x2e, 0x73, 0x5f, 0x53, 0xde, 0xeb, 0x88, 0x77, 0x31, 0x5c, 0xc1, 0xb0, 0xed, 0x80,
	0x41, 0x1a, 0x65, 0xb3, 0x0d, 0x86, 0xf8, 0xb9, 0x17, 0xee, 0xf8, 0xc7, 0xd8, 0xb5, 0x7e, 0xf7,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0x24, 0xcf, 0xa4, 0x0b, 0x06, 0x02, 0x00, 0x00,
}
