// Code generated by protoc-gen-go. DO NOT EDIT.
// source: network.proto

/*
Package d7024e is a generated protocol buffer package.

It is generated from these files:
	network.proto

It has these top-level messages:
	KademliaPacket
*/
package d7024e

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KademliaPacket struct {
	SourceAddress string `protobuf:"bytes,1,opt,name=SourceAddress" json:"SourceAddress,omitempty"`
	Procedure     string `protobuf:"bytes,2,opt,name=Procedure" json:"Procedure,omitempty"`
}

func (m *KademliaPacket) Reset()                    { *m = KademliaPacket{} }
func (m *KademliaPacket) String() string            { return proto.CompactTextString(m) }
func (*KademliaPacket) ProtoMessage()               {}
func (*KademliaPacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KademliaPacket) GetSourceAddress() string {
	if m != nil {
		return m.SourceAddress
	}
	return ""
}

func (m *KademliaPacket) GetProcedure() string {
	if m != nil {
		return m.Procedure
	}
	return ""
}

func init() {
	proto.RegisterType((*KademliaPacket)(nil), "d7024e.KademliaPacket")
}

func init() { proto.RegisterFile("network.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4b, 0x2d, 0x29,
	0xcf, 0x2f, 0xca, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0x31, 0x37, 0x30, 0x32,
	0x49, 0x55, 0x0a, 0xe1, 0xe2, 0xf3, 0x4e, 0x4c, 0x49, 0xcd, 0xcd, 0xc9, 0x4c, 0x0c, 0x48, 0x4c,
	0xce, 0x4e, 0x2d, 0x11, 0x52, 0xe1, 0xe2, 0x0d, 0xce, 0x2f, 0x2d, 0x4a, 0x4e, 0x75, 0x4c, 0x49,
	0x29, 0x4a, 0x2d, 0x2e, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x15, 0x14, 0x92, 0xe1,
	0xe2, 0x0c, 0x28, 0xca, 0x4f, 0x4e, 0x4d, 0x29, 0x2d, 0x4a, 0x95, 0x60, 0x02, 0xab, 0x40, 0x08,
	0x24, 0xb1, 0x81, 0x2d, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x86, 0xb1, 0x82, 0x75,
	0x00, 0x00, 0x00,
}
